# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"

[storage]
reserve-space = "0"

[storage.block-cache]
capacity = "15GB"

[raftstore]
capacity = {disk_avail}
hibernate-regions = false

[rocksdb]
max-open-files = 1000

[raftdb]
max-open-files = 1000
