# key \t value
dbgen_url_mac	https://download.pingcap.org/tiflash/mac/dbgen.tar.gz
dbgen_url	https://download.pingcap.org/tiflash/linux/dbgen.tar.gz
dists_dss_url_mac	https://download.pingcap.org/tiflash/mac/dists.dss
dists_dss_url	https://download.pingcap.org/tiflash/linux/dists.dss
upload_server_host_mac	http://139.219.11.38:8000
upload_server_host	http://139.219.11.38:8000
upload_server_route_mac	66nb8
upload_server_route	66nb8
