SELECT COUNT(*) FROM lineitem;
SELECT COUNT(*) FROM lineitem WHERE L_LINESTATUS = 'N';
SELECT * FROM lineitem LIMIT 1,1;
SELECT * FROM lineitem WHERE L_SHIPINSTRUCT = 'TAKE BACK RETURN';
SELECT L_RETURNFLAG,COUNT(*) AS c FROM lineitem WHERE L_SHIPDATE >= '1990-01-01' AND L_SHIPDATE <= '2000-01-01' GROUP BY L_RETURNFLAG ORDER BY c DESC;
SELECT L_RETURNFLAG,L_LINESTATUS,COUNT() AS c FROM lineitem GROUP BY L_RETURNFLAG,L_LINESTATUS ORDER BY c DESC LIMIT 100;
