SELECT COUNT(*) FROM lineitem;
SELECT COUNT(*) FROM lineitem GROUP BY L_LINESTATUS;
SELECT SUM(L_LINENUMBER) FROM lineitem;
SELECT L_SHIPDATE,L_SHIPINSTRUCT FROM lineitem WHERE L_SHIPDATE >= '1993-01-01';
SELECT * FROM lineitem LIMIT 1,1;
SELECT L_COMMENT FROM lineitem = 'DELIVER IN PERSON","REG AIR","ly pending foxes cajole';
SELECT * FROM lineitem WHERE L_SHIPINSTRUCT = 'TAKE BACK RETURN';
SELECT L_RETURNFLAG,COUNT(*) AS c FROM lineitem WHERE L_SHIPDATE >= '1990-01-01' AND L_SHIPDATE <= '2000-01-01' GROUP BY L_RETURNFLAG ORDER BY c DESC;
SELECT L_RETURNFLAG,L_LINESTATUS,COUNT() AS c FROM lineitem GROUP BY L_RETURNFLAG,L_LINESTATUS ORDER BY c DESC LIMIT 100;
SELECT L_LINESTATUS,COUNT(*) AS c FROM lineitem WHERE L_LINENUMBER >= 1 AND L_LINENUMBER <= 20 GROUP BY L_LINESTATUS ORDER BY c DESC LIMIT 10;

