tmp_path = "{tiflash_dir}/tmp"
display_name = "TiFlash"
default_profile = "default"
users_config = "users.toml"
path = "{tiflash_dir}/db"
capacity = "10737418240"
mark_cache_size = 5368709120
listen_host = "{tiflash_listen_host}"
tcp_port = {tiflash_tcp_port}
http_port = {tiflash_http_port}
interserver_http_port = {tiflash_interserver_http_port}

[flash]
tidb_status_addr = "{tiflash_tidb_addr}"
service_addr = "{tiflash_listen_host}:{tiflash_raft_and_cop_port}"

[flash.flash_cluster]
master_ttl = 60
refresh_interval = 20
update_rule_interval = 5
# this config should be ignored by latest tiflash version
cluster_manager_path = "{tiflash_dir}/tiflash/flash_cluster_manager"

[flash.proxy]
addr = "0.0.0.0:{proxy_port}"
advertise-addr = "{tiflash_listen_host}:{proxy_port}"
status-addr = "0.0.0.0:{proxy_status_port}"
advertise-status-addr = "{tiflash_listen_host}:{proxy_status_port}"
data-dir = "{tiflash_dir}/db/proxy"
config = "{tiflash_dir}/conf/proxy.toml"
log-file = "{tiflash_dir}/log/proxy.log"
log-level = "info"

[logger]
level = "debug"
log = "{tiflash_dir}/log/server.log"
errorlog = "{tiflash_dir}/log/error.log"
size = "500M"
count = 40

[application]
runAsDaemon = true

[raft]
kvstore_path = "{tiflash_dir}/kvstore"
pd_addr = "{tiflash_pd_addr}"
ignore_databases = "system,default"
storage_engine = "dt"

[status]
metrics_port = "{tiflash_listen_host}:{tiflash_status_port}"
