# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"

[storage]
reserve-space = "0"

[raftstore]
capacity = {disk_avail}
apply-pool-size = 4
store-pool-size = 4

[rocksdb]
max-open-files = 1000

[raftdb]
max-open-files = 1000

#[security.encryption]
#data-encryption-method = "aes256-ctr"
#data-key-rotation-period = "14d"

#[security.encryption.master-key]
#type = "file"
#path = "{integrated}/cipher-file-256"

#[security.encryption.previous-master-key]
#type = "plaintext"
