tmp_path = "{tiflash_dir}/tmp"
display_name = "TiFlash"
default_profile = "default"
users_config = "users.toml"
path = "{tiflash_dir}/db"
mark_cache_size = 5368709120
listen_host = "{tiflash_listen_host}"
tcp_port = {tiflash_tcp_port}
http_port = {tiflash_http_port}
interserver_http_port = {tiflash_interserver_http_port}

[flash]
tidb_status_addr = "{tiflash_tidb_addr}"
service_addr = "{tiflash_listen_host}:{tiflash_raft_and_cop_port}"
overlap_threshold = 0.6

[logger]
level = "trace"
log = "{tiflash_dir}/log/server.log"
errorlog = "{tiflash_dir}/log/error.log"
size = "4000M"
count = 10

[application]
runAsDaemon = true

[raft]
kvstore_path = "{tiflash_dir}/kvstore"
ignore_databases = "system"
storage_engine = "dt"

